name: Build
on: [push]

jobs:
  build-linux-stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast

  build-macos-stack:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast
