name: Build
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        ghc: ['8.10', '9.0']
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.4'
    - name: Update cabal package database
      run: |
        cabal update
        cabal freeze
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build
      run: |
        make

  build-linux-stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast

  build-macos-stack:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install stack
      run: which stack || curl -sSL https://get.haskellstack.org/ | sh
    - name: Install GHC
      run: stack setup
    - name: Build
      run: |
        stack build --fast
